googleapis/gax-python

- google/gax/path_template.py
- test/test_path_template.py
- tox.ini
Changes the literal regex to accept all non-token characters.
> Loosen literal restrictions

- google/gax/path_template.py
Change-Id: I6a85af5ff797b35a1e6f89da6e5633fd70f0661e
> Remove stale debug statements

- google/gax/api_callable.py
- test/test_api_callable.py
This change corresponds to a change in the codegen removing
"callable" versions of generated API methods. The standard
versions of generated methods may now be passed a CallOptions
object to perform the same configuration that previously had been
done through the callable methods.
- Revert renaming of ApiCallableDefault from CallOptions, which
conflicts with the new CallOptions object
- Add CallOptions object
- Add global value to indicate that a particular setting should
be inherited from defaults
- Add testing for CallOptions
> Permit configuration for noncallable methods

- google/gax/__init__.py
- google/gax/api_callable.py
- google/gax/bundling.py
- test/test_bundling.py
- test/test_gax.py
Status
- this is not complete yet
- additional features + unittests need to be added
- however, there should be enough to allow code-gen to incorporate this
The missing behaviour will be added in follow-up PRs
Change-Id: Ib6ab7db8a5947f6ea12ba6faa1202817f8dc6abc
> Begins to provide support for bundling

- CONTRIBUTING.rst
- README.rst
- google/gax/auth.py
- google/gax/grpc.py
- setup.py
- test/test_auth.py
- test/test_grpc.py
- Switch to grpc 0.13
- updates to the new gRPC credentials surface
Change-Id: Iec128db6e23fb2efd47ddfc2e47e22b08bc46ae7
> Update gRPC dependency

- .travis.yml
- google/gax/api_callable.py
- requirements.txt
- tox.ini
- also fixes a minor bug in api_callable
> Add a travis.yml file

- README.rst
Change-Id: I943b5baab8417fa3d9249d73fedd6dc94fc6d35b
> Add status badges to the README.rst

- google/gax/__init__.py
- google/gax/path_template.py
- test/test_path_template.py
Change-Id: I5d68b72a85f085ff63776e1e6c4c3cdc7a191f4f
> Allow percent encoded characters in path templates

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
- test/test_gax.py
Also moves some classes from gax.api_callable to gax. Note that this
change does not actually implement exponential backoff; most of the
retry config settings are ignored.
> Allows retry config to be passed to ApiCallable

- google/gax/path_template.py
- test/test_path_template.py
Remove support for custom verbs (only useful for HTTP).
Resolves #39
> Expand the accepted character set for literals

- google/gax/api_callable.py
- google/gax/bundling.py
- test/test_bundling.py
Also increases punctuation consistency in docs for bundling.py.
Fixes #42
> kwargs support for bundled requests

- google/gax/__init__.py
- google/gax/api_callable.py
- google/gax/bundling.py
- test/test_api_callable.py
Implements the exponential backoff algorithm for retrying.
> Implement retrying

- google/gax/__init__.py
Forgot to bump version last time.
> Bump the version

- google/gax/__init__.py
- google/gax/api_callable.py
- google/gax/config.py
- google/gax/errors.py
- google/gax/grpc.py
- test/test_api_callable.py
Wraps instaces of gRPC AbortionError during RPCs with GaxError.
> Wrap gRPC errors

- google/gax/__init__.py
- setup.py
This should resolve some installation-related bugs.
FYI: @vsubramani
> Update to the latest version of grpcio

- google/gax/__init__.py
- google/gax/path_template.py
- test/test_path_template.py
Fixes #93 
Corresponding codegen change is googleapis/toolkit#19
> Rename path template `instantiate` to `render`

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
Now this allows getting call options as an optional parameter
and changes its behavior.
In a part of #104 effort.
> Update the structure of api_callable.

- google/gax/api_callable.py
- google/gax/config.py
- google/gax/errors.py
- google/gax/grpc.py
> Relative imports

- MANIFEST.in
- docs/conf.py
- google/gax/__init__.py
- google/gax/retry.py
- setup.py
https://github.com/googleapis/googleapis/issues/245
> Rollback #151

- google/gax/__init__.py
- google/gax/api_callable.py
- google/gax/bundling.py
- google/gax/grpc.py
- google/gax/path_template.py
- google/gax/retry.py
- google/gax/utils/metrics.py
- scripts/run_pylint.py
this is mostly just docstring updates.
> Fix lint for the primary package
