- google/gax/__init__.py
- setup.py
- reflects the fact that ApiCallableDefaults changed to CallOptions
- also adds the link to the public github repo in setup.py
> Update the version

- google/gax/api_callable.py
- test/test_api_callable.py
The settings for ApiCallable are now passed into the constructor via a
CallOptions object. Additionally, removes the idempotent_callable()
method; idempotent callables are now constructed through an optional
parameter to the ApiCallable constructor.
> Refactor ApiCallable to use CallOptions

- docs/index.rst
- google/gax/__init__.py
- google/gax/api_callable.py
- google/gax/bundling.py
- test/test_bundling.py
- Adds bundling.Event that wraps a threading.Event
* this allows notification on request completion using the
methods of threading.Event
- bundling.Event provides additional behaviour
* it holds the cancellation function and result as attributes
* the result holds the per-bundle-call result
* this means callers no longer need to hold the out_deque
- this simplifies bundling.Executor#schedule; this is update to
just return a bundling.Event
- Adds an optional subresponse field to BundleDescriptor
- Adds supports for this to Task#run
* when the subresponse_field is present, the response is demultiplexed
> Simplify bundling executor schedule

- google/gax/path_template.py
- test/test_path_template.py
Add t_error to catch illegal token exceptions.
> Restrict literal regex according to RFC spec

- google/gax/api_callable.py
Bundling thresholds are configurable on a per-method (rather than per-
API) basis, so these objects should be set in CallOptions, rather than
ApiCallDefaults.
Fixes #23.
> Move Bundle{Options,Descriptor} into CallOptions

- google/gax/api_callable.py
- test/test_api_callable.py
Provides access to bundling through ApiCallable. Replaces
ApiCallDefaults with CallSettings, which corresponds to a change
in the code generation to pass bundling settings through to
ApiCallable.
> Update to support bundling

- google/gax/__init__.py
- google/gax/bundling.py
- test/test_api_callable.py
- test/test_bundling.py
- test/test_gax.py
Clarifies whether "message" is used in the sense of an element in a
repeated field, or in the sense of a proto message; also brings
terminology in line with code generator terminology.
Note: I have attempted to use term "element" to refer to a generic
member of a repeated field, but certain specific elements _may_ be
messages as well (e.g., in pubsub) so I do not see the presence of
both terms in the `test_bundling` module to be contradictory.
Fixes #36
> Rename bundling fields

- google/gax/api_callable.py
- google/gax/path_template.py
- test/test_api_callable.py
Replaced "impossible match" by actual description of the error.
Also fixes #51 (a retrying bug).
> Increase usefulness of a PathTemplate error; fix retrying bug

- google/gax/__init__.py
- google/gax/config.py
ExpirationError sometimes seems to have no status code; force it
to map to DEADLINE_EXCEEDED.
fixes #53
> Recognize ExpirationError, even if no status code

- google/gax/grpc.py
"DNS" was used where "domain name" was meant.
> Fix incorrect documentation

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
Changes the descriptors from required to optional parameters to
`construct_settings`. This is nicer for APIs that either do not
support page streaming or bundling.
> Do not require descriptors for construct_settings

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
- replaces the ApiCallable class with a decorator-style function that
does the same thing
> Refactor: replace ApiCallable with a function

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
The currently, the code generator uses Guava's CaseFormat to convert
the CamelCase method names defined in the IDL to more Pythonic
snake_case. However, this conversion is not reflected in the client
config, since that config is language-independent. Instead, we have
GAX do the conversion in a format that is intended to match the Guava
case formatting exactly.
(Note that it is necessary for Guava CaseFormat and GAX to provide
identical behavior, or else the client config will not be parsed
properly.)
Fixes #73.
> Convert CamelCase method name to snake_case

- google/gax/__init__.py
- google/gax/api_callable.py
Our field names in Python differ slightly from the JSON config names.
> Fix BundleOptions construction

- google/gax/__init__.py
- google/gax/config.py
- google/gax/grpc.py
Config should not contain any implementation itself, only serve as an
interface to functionality whose implementation is protocol-specific.
> Move code from `config` to `grpc`

- docs/index.rst
Without this change, links to GaxError don't show up in package documentation
> Add the errors module to the documentation

- docs/conf.py
- google/gax/__init__.py
- google/gax/api_callable.py
CallOptions is very visible in generated docs like
http://pythonhosted.org/gax-google-pubsub-v1, but clicking on it does
not link to a good explanation.
This
- fixes the doc-gen so that constructor comments and __init__ comments
are both included
- adds more details
Also:
- fixes a few other referencing issues in the docs
> Explain CallOptions in more detail.

- google/gax/__init__.py
- google/gax/bundling.py
- test/test_bundling.py
- Add `is_bundling` field to CallOptions. This field is False by
default and must be explicitly enabled for a call to bundle.
- Fix a bug (#91) where proto repeated field was assigned to instead of
extended; proto does not support repeated field assignment.
> Disable bundling by default, fix bundling bug

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
- test/test_gax.py
Fixes #86
Now return an iterable over pages of the response resource field,
rather than the return type, for page stream-able calls where page
streaming is disabled.
Note that this removes the ability to get a standard gRPC/proto
response from any call that is capable of page streaming.
This is intended to demonstrate one of the proposals from #86
> Change page-streaming behavior

- google/gax/__init__.py
- test/test_gax.py
It shouldn't be possible to construct a CallOptions with both retry
and timeout.
Fixes #98 
FYI: @garrettjonesgoogle
> Validate CallOptions constructor

- google/gax/__init__.py
Previously, it refered to an outdated implementation of page
streaming.
Fixes #100
> Fix CallOptions snippet

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
Based on the discussion of #95 and googleapis/toolkit#70 --
this changes the interface of construct_settings a bit.
The new interface does not have the override parameters for
retrying and bundling anymore. Instead, it has a single
config_override that has the same strucure as client_config has.
API users can specify a copy of default config data with a few
modifications, but if the user-supplied config does not specify
some data, this will fall back to the default config, so
users can safely supply a part of the client config, just for
their edits.
> Update construct_settings overrides

- CONTRIBUTING.rst
#111 requires the `BREW_HOME` environment variable to be
set in order for tests to run. Make a note of this in the docs.
> Note environment variable for tests

- google/gax/__init__.py
Forgot to do this last commit.
After this, I will update packman to depend on the latest version of gax-python.
> Bump the version

- google/gax/__init__.py
- test/test_api_callable.py
\#107 means that `page_token` can sometimes be set to `None` instead
of `INITIAL_PAGE` when making the first call. This results in a
protobuf type error.
> Bug fix for page streaming

- google/gax/__init__.py
- google/gax/api_callable.py
- test/test_api_callable.py
- test/test_gax.py
This allows any future renaming/revision not to be a breaking change.
Fixes #112
> Make _CallSettings private

- google/gax/__init__.py
- google/gax/grpc.py
- setup.py
- test-requirements.txt
- test/test_grpc.py
Also bump dependency on grpc up to 1.0.0.
Fixes #126
> Remove references to grpc.beta

- google/gax/__init__.py
- google/gax/grpc.py
- test/test_grpc.py
Previously, we were catching and wrapping AbortionError, which is no
longer used by gRPC. Instead, use RpcError.
/cc @dhermes
Fixes #129 and #130
> Fix error-handling to use new gRPC exceptions

- google/gax/api_callable.py
- google/gax/config.py
- google/gax/errors.py
- google/gax/grpc.py
- test/test_api_callable.py
Fixes #123
The second part of this is to modify GAPIC (in the `toolkit` repo) so that all API call methods that take arguments specify in the docstring that they may raise `ValueError`. This is done at https://github.com/googleapis/toolkit/pull/491.
> Wrap INVALID_ARGUMENT status as ValueError

- google/gax/__init__.py
Fixes "No handlers found for logger google.gax" error
> Add logging.NullHandler

- google/gax/utils/oneof.py
- tests/test_utils_oneof.py
Previously, it checked truthiness, which doesn't correspond accurately
to fields being set or not set in the GAPIC request.
> Switch oneof validation to check none-ness

- MANIFEST.in
- setup.py
* Don't include tests in the binary (wheel) distribution.
* Include tests in the source distribution.
* Remove (seemingly?) unneeded package_dir.
* Use io.open over open for proper encoding.
> Fix packaging setup

- google/gax/api_callable.py
- tests/test_api_callable.py
Merges tuples in settings.kwargs['metadata'] propertly. For example for the input of:
```python
options.kwargs = {metadata: [('x-goog-api-client', 'val1')]}
settings.kwargs = {metadata: [('google-cloud-resource-prefix', 'val2'), ('x-goog-api-client', 'val3')]}
```
The merged result will be:
```python
this_settings.kwargs = {metadata: [('x-goog-api-client', 'val1'), ('google-cloud-resource-prefix', 'val2')]}
```
> Fix x-goog-api-client header inconsistency for spanner client
